//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using MySql.Data.MySqlClient;

	public class DbManager
	{
	static float GAME_VERSION = 1.0f; //viene aggiornata ad ogni modifica sostanziale (per adesso possiamo aggiornarlo in base ai progressi nel db)
	//static MySqlConnection myConnection = null;
    static MySqlConnection myConnection = null;
	private DbManager ()
	{
        myConnection = new MySqlConnection("SERVER=localhost;DATABASE=scuola_progetto;UID=root;PASSWORD=ascent;");
	}
		
	public static void setInstance(){
		if(myConnection==null)
			new DbManager();
	}
	public static void savePlayer(string sql){
		myConnection.Open ();
		MySqlCommand com = new MySqlCommand (sql, myConnection);
		com.ExecuteNonQuery ();
		myConnection.Close ();
	}
	public static string loadPlayer(string playerName){
		myConnection.Open ();
        string sql = "SELECT level, exp, health, maxhealth, position_x, position_y, position_z, orientation_x, orientation_y, orientation_z FROM player WHERE name='" + playerName + "';";
		MySqlCommand com = new MySqlCommand (sql, myConnection);
		MySqlDataReader reader = com.ExecuteReader ();
		string result = "";

		if (reader.Read ()) {
            result = reader["level"] + "-" + reader["exp"] + "-" + reader["health"] + "-" + reader["maxhealth"] + "-" + reader["position_x"] + "-" + reader["position_y"] + "-" + reader["position_z"] + "-" + reader["orientation_x"] + "-" + reader["orientation_y"] + "-" + reader["orientation_z"];
		}
		myConnection.Close ();
		return result;
	}
	//La versione del game andrà di pari passo con quella del DB, quando ci sarà una versione di gioco diversa verrà di conseguenza aggiornato anche il db(anche se non ci sono
	//aggiornamenti verrà comunque aggiornata la versione nel DB) questo metodo ci consente di tenere aggiornato il DB di qualsiasi versione di gioco e senza metter mano
	//a client MySql o mettere bottoni
	bool update(){
		float currentGV = 0;
		float currentDB = 0;
		string sql = "SELECT * FROM version;";
		MySqlCommand com = new MySqlCommand(sql, myConnection); 
		MySqlDataReader reader = com.ExecuteReader ();
		//----- controlla se c'è già una riga nella tabella versione, se non c'è la inserisce con la versione di gioco corrente e db con solo le tabelle create
		// e ritorna false per continuare il ciclo di aggiornamento
		if (!reader.HasRows) {
			MySqlCommand Ins = new MySqlCommand ("INSERT INTO version (game_version, db_version) VALUES(" + GAME_VERSION + ", 1.0);", myConnection);
			Ins.ExecuteNonQuery();
			if(GAME_VERSION > 1.0f)
				return false;
			return true;
		}
		else{
			if(reader.Read()){
				currentGV = reader.GetFloat(2);
				currentDB = reader.GetFloat(3);
				if(currentGV < GAME_VERSION){    //----- Aggiorna nel db la versione di gioco con quella corrente
					MySqlCommand Ins = new MySqlCommand ("UPDATE version SET game_version = " + GAME_VERSION + ");" , myConnection);
					Ins.ExecuteNonQuery();
					currentGV = GAME_VERSION;
				}

			}
	    }
		if (currentGV > currentDB) {  //Qui all'interno ci andranno i diversi update per versione di gioco
			if(currentDB == 1.0f){
				//Qui vanno inseriti gli aggiornamenti poi con la query sotto viene aggiornata la versione del db
				//MySqlCommand upda = new MySqlCommand ("UPDATE version SET db_version = 1.1 WHERE id = 1;", myConnection);
				//upda.ExecuteNonQuery();
				//currentDB = 1.1f;
			}
			else if(currentDB == 1.1f){
				//Qui vanno inseriti gli aggiornamenti poi con la query sotto viene aggiornata la versione del db
				//MySqlCommand upda = new MySqlCommand ("UPDATE version SET db_version = 1.2 WHERE id = 1;", myConnection);
				//upda.ExecuteNonQuery();
				//currentDB = 1.2f;
			}
		
		}
		if (currentDB < currentGV) //se il db non è ancora all'ultima versione ritorna false per continuare il ciclo
			return false;
		
	    return true;

	}

}

