//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using Mono.Data.Sqlite;

	public class DbManager
	{
	static SqliteConnection myConnection = null;
	private DbManager ()
	{
		//SqliteConnection.CreateFile ("Assets/DB/virus.sqlite");
		myConnection = new SqliteConnection("URI=file:Assets/DB/virus.sqlite,version=3");
		createTables ();
	}
		
	public static void setInstance(){
		if(myConnection==null)
			new DbManager();
	}
	private static void createTables(){
		myConnection.Open ();
		string playerTable = "CREATE TABLE IF NOT EXISTS player ( " +
							"name varchar(20), " +
							"level int, " +
							"exp int, " +
							"health int, " +
							"maxhealth int, " +
							"PRIMARY KEY (name)) ";
		SqliteCommand com = new SqliteCommand (playerTable, myConnection);
		com.ExecuteNonQuery ();
		myConnection.Close ();
	}
	public static void savePlayer(string sql){
		myConnection.Open ();
		SqliteCommand com = new SqliteCommand (sql, myConnection);
		com.ExecuteNonQuery ();
		myConnection.Close ();
	}

}

